# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:
    - env
    - locale
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - pod --version
    - pod setup --silent > /dev/null
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail

    - echo Check if the library described by the podspec can be built
    - pod lib lint --allow-warnings

    - echo Build the Demo apps
    - pod install --project-directory=Example
    - xcodebuild clean -workspace Example/MXADS.xcworkspace -scheme 'MXADS-Example' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
    
after_success:
    - bash <(curl -s https://codecov.io/bash)